#!/usr/bin/make

# Install arduino-mk
# Edit /usr/share/arduino/Arduino.mk to replace "WProgram.h" with "Arduino.h"

BOARD_TAG = mega2560
ARDUINO_PORT = /dev/ttyACM0
ARDUINO_DIR = /usr/share/arduino
#ARDUINO_DIR = /home/local/ANT/averdow/Downloads/arduino-0023-64
ARDUINO_LIBS = SPI LiquidCrystal

include /usr/share/arduino/Arduino.mk
